# Generated by Django 3.2.4 on 2021-06-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdWordsCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('access_code', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
            ],
        ),
    ]
