# Generated by Django 3.2.4 on 2021-07-01 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adwordscredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adwordscredentials',
            name='username',
        ),
        migrations.AddField(
            model_name='adwordscredentials',
            name='mytoken',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
