# Generated by Django 3.2.4 on 2021-07-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210701_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiForgeryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytoken', models.CharField(max_length=600)),
                ('passthrough_val', models.CharField(max_length=600)),
            ],
        ),
    ]
