# Generated by Django 3.2.4 on 2021-07-06 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_antiforgerytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiforgerytoken',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
    ]
