# Generated by Django 3.2.4 on 2021-07-08 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_antiforgerytoken_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antiforgerytoken',
            old_name='code',
            new_name='google_access_code',
        ),
    ]
