# Generated by Django 3.2.4 on 2021-07-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_code_antiforgerytoken_google_access_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adwordscredentials',
            old_name='access_code',
            new_name='google_access_code',
        ),
    ]
