# Generated by Django 3.2.4 on 2021-07-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_access_code_adwordscredentials_google_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytoken', models.CharField(max_length=500)),
                ('refreshToken', models.CharField(max_length=500)),
            ],
        ),
    ]
