# Generated by Django 3.2.4 on 2021-07-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytoken', models.CharField(max_length=500)),
            ],
        ),
    ]
