# Generated by Django 3.2.4 on 2021-08-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_keywordthemesrecommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(max_length=500)),
                ('language_code', models.CharField(max_length=500)),
                ('country_code', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
    ]
