# Generated by Django 3.2.4 on 2021-08-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_locationrecommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsAccountCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(max_length=500)),
                ('account_name', models.CharField(max_length=500)),
                ('currency', models.CharField(max_length=10)),
                ('time_zone', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=500)),
            ],
        ),
    ]
