# Generated by Django 3.2.4 on 2021-08-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_googleadsaccountcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleadsaccountcreation',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
