# Generated by Django 3.2.4 on 2021-08-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_googleadsaccountcreation_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadsaccountcreation',
            name='mytoken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
