# Generated by Django 3.2.4 on 2021-09-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_newaccountcustomerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetKeywordThemesRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(max_length=500)),
                ('keyword_text', models.CharField(max_length=500)),
                ('country_code', models.CharField(max_length=500)),
                ('language_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='keywordthemesrecommendations',
            old_name='country_code',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='keywordthemesrecommendations',
            old_name='keyword_text',
            new_name='resource_name',
        ),
        migrations.RemoveField(
            model_name='keywordthemesrecommendations',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='keywordthemesrecommendations',
            name='refreshToken',
        ),
        migrations.AlterField(
            model_name='reporting',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
