# Generated by Django 3.2.4 on 2021-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210906_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetBudgetRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(blank=True, max_length=500)),
                ('customer_id', models.CharField(max_length=500)),
                ('display_name', models.TextField()),
                ('language_code', models.CharField(max_length=500)),
                ('country_code', models.CharField(max_length=500)),
                ('landing_page', models.CharField(max_length=500)),
                ('geo_target_names', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='getkeywordthemesrecommendations',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='locationrecommendations',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
