# Generated by Django 3.2.4 on 2021-09-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210908_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateSmartCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(blank=True, max_length=500)),
                ('customer_id', models.CharField(max_length=500)),
                ('display_name', models.TextField()),
                ('language_code', models.CharField(max_length=500)),
                ('country_code', models.CharField(max_length=500)),
                ('landing_page', models.CharField(max_length=500)),
                ('geo_target_names', models.TextField()),
                ('selected_budget', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('business_name', models.CharField(max_length=500)),
                ('headline_1_user', models.CharField(max_length=500)),
                ('headline_2_user', models.CharField(max_length=500)),
                ('headline_3_user', models.CharField(max_length=500)),
                ('desc_1_user', models.CharField(max_length=500)),
                ('desc_2_user', models.CharField(max_length=500)),
                ('campaign_name', models.CharField(max_length=500)),
            ],
        ),
    ]
