# Generated by Django 3.2.4 on 2021-11-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_campaignname'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditCampaignBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(blank=True, max_length=500)),
                ('customer_id', models.CharField(max_length=500)),
                ('campaign_id', models.CharField(max_length=500)),
                ('new_budget', models.CharField(max_length=500)),
                ('budget_id', models.CharField(max_length=500)),
            ],
        ),
    ]
