# Generated by Django 3.2.4 on 2021-11-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_editcampaignbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(blank=True, max_length=500)),
                ('customer_id', models.CharField(max_length=500)),
                ('campaign_id', models.CharField(max_length=500)),
                ('date_range', models.CharField(max_length=500)),
            ],
        ),
    ]
