# Generated by Django 3.2.4 on 2021-12-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_searchtermsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='getkeywordthemesrecommendations',
            name='business_location_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='getkeywordthemesrecommendations',
            name='business_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='getkeywordthemesrecommendations',
            name='customer_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='getkeywordthemesrecommendations',
            name='final_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='getkeywordthemesrecommendations',
            name='keyword_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
