# Generated by Django 3.2.4 on 2021-12-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20211202_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='getkeywordthemesrecommendations',
            name='geo_target_names',
            field=models.TextField(blank=True),
        ),
    ]
