# Generated by Django 3.2.4 on 2022-01-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_editadcreative'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditKeywordThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(blank=True, max_length=500)),
                ('customer_id', models.CharField(max_length=500)),
                ('campaign_id', models.CharField(max_length=500)),
                ('display_name', models.TextField()),
            ],
        ),
    ]
