# Generated by Django 3.2.4 on 2022-02-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_editgeotargets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editgeotargets',
            name='new_geo_target_names',
            field=models.TextField(),
        ),
    ]
