# Generated by Django 3.2.4 on 2022-05-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_editgeotargets_new_geo_target_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditAdSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(blank=True, max_length=500)),
                ('customer_id', models.CharField(max_length=500)),
                ('campaign_id', models.CharField(max_length=500)),
                ('mon_start', models.CharField(blank=True, max_length=500)),
                ('mon_end', models.CharField(blank=True, max_length=500)),
                ('tue_start', models.CharField(blank=True, max_length=500)),
                ('tue_end', models.CharField(blank=True, max_length=500)),
                ('wed_start', models.CharField(blank=True, max_length=500)),
                ('wed_end', models.CharField(blank=True, max_length=500)),
                ('thu_start', models.CharField(blank=True, max_length=500)),
                ('thu_end', models.CharField(blank=True, max_length=500)),
                ('fri_start', models.CharField(blank=True, max_length=500)),
                ('fri_end', models.CharField(blank=True, max_length=500)),
                ('sat_start', models.CharField(blank=True, max_length=500)),
                ('sat_end', models.CharField(blank=True, max_length=500)),
                ('sun_start', models.CharField(blank=True, max_length=500)),
                ('sun_end', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
