# Generated by Django 3.2.4 on 2022-05-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20220506_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkToManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(max_length=500)),
                ('customer_id', models.CharField(max_length=500)),
            ],
        ),
    ]
