# Generated by Django 3.2.4 on 2022-06-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_reporting_mytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktomanager',
            name='mytoken',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
