# Generated by Django 3.2.4 on 2022-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_linktomanager_mytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrecommendations',
            name='mytoken',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
