# Generated by Django 3.2.4 on 2022-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20220617_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadsaccountcreation',
            name='customer_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
